# Generated by Django 4.2 on 2023-05-04 05:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pricetag", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="device_serial",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="device",
            name="device_status_id",
            field=models.CharField(blank=True, default="", max_length=5),
        ),
        migrations.AlterField(
            model_name="device",
            name="device_name",
            field=models.CharField(max_length=50),
        ),
    ]
