# Generated by Django 4.2 on 2023-05-04 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pricetag", "0002_device_device_serial_device_device_status_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="device",
            options={"verbose_name": "Устройство", "verbose_name_plural": "Устройство"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Продукт", "verbose_name_plural": "Продукты"},
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "battery_status",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "wifi_status",
                    models.CharField(blank=True, default="", max_length=180),
                ),
                (
                    "charg_status",
                    models.CharField(blank=True, default="", max_length=180),
                ),
                (
                    "device_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status",
                        to="pricetag.device",
                    ),
                ),
            ],
            options={
                "verbose_name": "Статус",
                "verbose_name_plural": "Статусы",
            },
        ),
    ]
