# Generated by Django 4.2 on 2023-05-05 09:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pricetag", "0003_alter_device_options_alter_product_options_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="status",
            options={"verbose_name": "Статус", "verbose_name_plural": "Статус"},
        ),
        migrations.RenameField(
            model_name="status",
            old_name="device_id",
            new_name="device_name",
        ),
    ]
