# Generated by Django 4.2 on 2023-05-05 09:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pricetag", "0004_alter_status_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="status",
            old_name="device_name",
            new_name="device_id",
        ),
    ]
