# Generated by Django 4.2 on 2023-05-05 09:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pricetag", "0005_rename_device_name_status_device_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="status",
            old_name="device_id",
            new_name="device_name",
        ),
    ]
